

```{r}
library(MASS)
  (dnorm(1, 0, 4) * dnorm(2, 0, 4)) / (dnorm(1, 0, 1) * dnorm(2, 0, 1) + dnorm(1, 0, 4) * dnorm(2, 0, 4))
```
```{r}
post = function (x) {
  plus = dnorm(x[1], 0, 4) * dnorm(x[2], 0, 4)
  minus = dnorm(x[1], 0, 1) * dnorm(x[2], 0, 1)
  
  return (plus / (plus + minus))
} 

gel = seq(-4, 4, by=.15)

grid = expand.grid(gel, gel)

res = apply(grid, MARGIN=1, FUN=post)
matrixed = matrix(res, nrow=(length(gel)))

persp(gel, gel, matrixed, xlab = "x[1]", ylab= "x[2]", zlab="P", col="salmon", phi = 40, theta = 35)

```
```{r}
  sigm = matrix(c(1,0,0,1), nrow=2)
  sigma = matrix(c(16,0,0,16), nrow=2)
  samples = mvrnorm(simcount, c(0,0), sigm)
  sampless = mvrnorm(simcount, c(0,0), sigma)
  s = samples * sampless
  denssi = kde2d(s[,1], s[,2])
  persp(denssi)
```

```{r}
  avg = c()
  for (k in 0: 20) {
    classget = function() {
      return (sample(0:2, size=1, replace=TRUE, prob=c(0.4,0.3,0.3))  )
    }
  
    xget = function(class) {
      two = c(0.6, 0.1, 0.1, 0.1, 0.1, 0.0)
      one = c(0.2, 0.1, 0.4, 0.2, 0.0, 0.1)
      three = c(0.1, 0.4, 0.3, 0.0, 0.2, 0.0)
      probs = one
      
      if (class == 1) probs = two
      if (class == 2) probs = three
      
      return (expand.grid(0:1,0:2)[sample(1:6, 1, replace=TRUE, prob=probs),]  )
    }  
    
    xs = c()
    ys = c()
    
    for (i in 0:99) {
      y = classget()
      ys = c(ys, y)
      x = xget(y)
      xs = c(xs, x)
    }
    
    # xs = matrix(xs, nrow=100)
    # sum(xs[,1] == 0 & xs[,2] == 0)
    count = 0
    
    for (i in 0:99) {
      if (xs[i * 2 + 1] == 0 && xs[ i * 2 + 2] == 0 ) {
        count = count + 1
      }
    }
    
    avg = c(avg, count)  
  }

  mean(avg)
  hist(ys)

```

```{r}
  classifier = function(X, Y, a = 1) {
    n = length(Y)
    likelihood1 = vector("list", length = 3)
    likelihood2 = vector("list", length = 3)
    xs = c(2,3)
    
    prior = c(0, 0, 0)
    
    for (i in 0:2) {
      nc = sum(Y == i)
      prior[i + 1] = (nc + a) / (n + 3*a)
      for (j in 1:2) {
        for (k in 0:2) {
          total = 0
          for (xxx in 1:n) {
            if ((X[(xxx-1) * 2 + 2] == k) && (Y[xxx] == i)) total = total + 1
          }
          if (j == 1) {
            likelihood1[[i + 1]][[k + 1]] = ((total + a) / (nc + xs[j] * a))
          } else {
            likelihood2[[i + 1]][[k + 1]] = ((total + a) / (nc + xs[j] * a))
          }
        }
      }
    }
    
    return (list(lh1 = likelihood1, lh2 = likelihood2, prior = prior))
  }

  

  classified = classifier(xs, ys)
  
  classified
```

```{r}
  classified$lh1
  classified$lh2
  classified$prior
```

```{r}
predictions = function(model, XX) {
  n = length(XX) / 2
  probmatrix = matrix(numeric(n * 3), nrow = n, ncol = 3)
  
  for (i in 1:n) {
    for (c in 1:3) {
      probmatrix[i, c] = model$prior[c]
      for (j in 1:2) {
          index = XX[[(i - 1) * 2 + 1 + (j - 1)]]
          #print(model$lh1[[c]][[index]])
          if (j == 1) {
            probmatrix[i, c] = probmatrix[i, c] * model$lh1[[index + 1]][[c]]
          } else {
            probmatrix[i, c] = probmatrix[i, c] * model$lh2[[index + 1]][[c]]
          }
      }
    }
  }
  
  return (probmatrix)
}
```

```{r}
  num = 10000
  avg = c()
  classget = function() {
    sample(0:2, size=1, replace=TRUE, prob=c(0.4,0.3,0.3))  
  }

  xget = function(class) {
    two = c(0.6, 0.1, 0.1, 0.1, 0.1, 0.0)
    one = c(0.2, 0.1, 0.4, 0.2, 0.0, 0.1)
    three = c(0.1, 0.4, 0.3, 0.0, 0.2, 0.0)
    probs = one
    
    if (class == 1) probs = two
    if (class == 2) probs = three
    
    expand.grid(0:1,0:2)[sample(1:6, 1, replace=TRUE, prob=probs),]  
  }  
  
  xs = c()
  ys = c()
  
  for (i in 0:num) {
    y = classget()
    ys = c(ys, y)
    x = xget(y)
    xs = c(xs, x)
  }
  
  # xs = matrix(xs, nrow=100)
  # sum(xs[,1] == 0 & xs[,2] == 0)
  count = 0
  
  for (i in 0:num) {
    if (xs[i * 2 + 1] == 0 && xs[ i * 2 + 2] == 0 ) {
      count = count + 1
    }
  }
  
  xxs = xs
  yys = ys
  
  avg = c(avg, count) 

  mean(avg)
  hist(ys)
  #m = matrix(xs, nrow=2)
```

```{r}
  a = predictions(classified, xs)
  yhat = max.col(a)
  sum(yhat == ys) / length(ys)
```

```{r}
  perf = c()
  lperf = c()
  vals = c(26, 50, 100, 200, 400, 800, 1600, 3200, 6400)
  for (num in vals) {
    avg = c()
    
    xs = c()
    ys = c()
    
    for (i in 0:num) {
      y = classget()
      ys = c(ys, y)
      x = xget(y)
      xs = c(xs, x[1], x[2])
    }
    
    # xs = matrix(xs, nrow=100)
    # sum(xs[,1] == 0 & xs[,2] == 0)
    count = 0
    
    for (i in 0:num) {
      if (xs[i * 2 + 1] == 0 && xs[ i * 2 + 2] == 0 ) {
        count = count + 1
      }
    }
  
    classed = classifier(unlist(xs), ys, 1)
    pred = predictions(classed, xxs)
    yhat = max.col(pred)
    res = sum(yhat == yys) / length(yys)
    
    perf = c(perf, res)
    
    train = data.frame(Y = ys, X1 = factor(unlist(xs[c(TRUE, FALSE)])), X2 = factor(unlist(xs[c(FALSE, TRUE)])))
    
    library('nnet')
    logf = multinom(Y ~ X1 + X2, data = train, trace = FALSE)
    yhat = predict(logf, X = data.frame(X1 = factor(unlist(xxs[c(TRUE, FALSE)])), X2 = factor(unlist(xxs[c(FALSE, TRUE)]))))
    
    lper = sum(yhat == yys)
    lper = lper / length(yys)
    lperf = c(lperf, lper)
  }
  plot(vals, perf, type='l')
  plot(vals, lperf, type='l')
```

```{r}
  ma = matrix(c(1,3,5,2,4,6,7,8,9,0), nrow=5)
  tr = t(ma)
  ma
  t(ma)
  ma %*% tr 
  ma %*% tr %*% ma
```

