

```{r}
  k_means = function(k, X, iters, cents=NULL) {
    rows = nrow(X)
    cols = ncol(X)
    Y = NULL
    if (is.null(cents)) {
      cents = matrix(numeric(k * rows), nrow=rows)
      Y = round(runif(cols, 0, k - 1)) + 1
    }
    Y_old = NULL
    
    for (iter in 1: iters) {
      # Calculate centroids
      if (!is.null(Y)) {
        for (i in 1:k) {
          cents[,i ] = rowMeans(X[ , Y == i, drop=FALSE])
          Y_old = Y
        }
      }
      
      # Get distances to each class, each row is distance to centroid of that class
      dist = matrix(numeric(k*cols), nrow = k)
      for (i in 1:k) {
        dist[i,] = -colSums((X - cents[ , i])^2)
      }
      
      # Get class for each element from distances by transposing and getting the max of columns for each element
      Y = max.col(t(dist))
      
      if (identical(Y, Y_old)) {
        print(paste('Done on iteration ', iter))
        return (list(Y=Y, cents=cents))
      }
    }
    print(paste('Done on iteration ', iter))
    return (list(Y=cents_new, d=dist))
  } 
```

```{r}
cols = 300
entries = 2
X = matrix(rnorm(entries * cols), nrow = entries)

par(mfrow = c(2,2))
for(i in 1:4) {
    km = k_means(3, X, 100)
    plot(X[1, ], X[2, ], col = km$Y+1)
    lines(km$cents[1, ], km$cents[2, ], type = 'p', lwd = 4, col='black')
}
```
```{r}
# Load the MNIST digit recognition dataset into R
# http://yann.lecun.com/exdb/mnist/
# assume you have all 4 files and gunzip'd them
# creates train$n, train$x, train$y  and test$n, test$x, test$y
# e.g. train$x is a 60000 x 784 matrix, each row is one digit (28x28)
# call:  show_digit(train$x[5,])   to see a digit.
# brendan o'connor - gist.github.com/39760 - anyall.org

load_mnist <- function() {
  load_image_file <- function(filename) {
    ret = list()
    f = file(filename,'rb')
    readBin(f,'integer',n=1,size=4,endian='big')
    ret$n = readBin(f,'integer',n=1,size=4,endian='big')
    nrow = readBin(f,'integer',n=1,size=4,endian='big')
    ncol = readBin(f,'integer',n=1,size=4,endian='big')
    x = readBin(f,'integer',n=ret$n*nrow*ncol,size=1,signed=F)
    ret$x = matrix(x, ncol=nrow*ncol, byrow=T)
    close(f)
    ret
  }
  load_label_file <- function(filename) {
    f = file(filename,'rb')
    readBin(f,'integer',n=1,size=4,endian='big')
    n = readBin(f,'integer',n=1,size=4,endian='big')
    y = readBin(f,'integer',n=n,size=1,signed=F)
    close(f)
    y
  }
  train <<- load_image_file('mnist/train-images-idx3-ubyte')
  test <<- load_image_file('mnist/t10k-images-idx3-ubyte')
  
  train$y <<- load_label_file('mnist/train-labels-idx1-ubyte')
  test$y <<- load_label_file('mnist/t10k-labels-idx1-ubyte')  
}


show_digit <- function(arr784, col=gray(12:1/12), ...) {
  image(matrix(arr784, nrow=28)[,28:1], col=col, ...)
}

# load_mnist()
```

```{r}
n_train = 10000
X = t(train$x[1:n_train, ])
show_digit(X[ ,5])
```

```{r}
  par(mfrow = c(2,5))
  cents = matrix(numeric(10 * nrow(X)), ncol = 10)
  for(i in 1:10) {
    cents[ ,i] = X[ ,i]
  }
  
  res = k_means(10, X, 1000, cents)
  
  for (i in 1:10) {
    show_digit(X[,i])  
  }  
```

```{r}
  par(mfrow = c(10,15), mar = c(0,0,0,0))
  
  for (i in 1:10) {
    show_digit(res$cents[,i], axes=FALSE)
    
    for (j in 1:14) {
      show_digit(X[ , which(res$Y == i)[j]], axes=FALSE)
    }
  }
```

```{r}
  par(mfrow = c(2,5))
  cents = matrix(numeric(10 * nrow(X)), ncol = 10)
  for(i in 1:10) {
    cents[ ,i] = X[ , which(train$y[1:n_train] == (i - 1))[1]]
  }
  
  res_centered = k_means(10, X, 1000, cents)
  
  for (i in 1:10) {
    show_digit(cents[,i])
  }
```

```{r}

  par(mfrow = c(10,15), mar = c(0,0,0,0))
  
  for (i in 1:10) {
    show_digit(res_centered$cents[,i], axes=FALSE)
    
    for (j in 1:14) {
      show_digit(X[ , which(res_centered$Y == i)[j]], axes=FALSE)
    }
  }

```
